on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            mkdir pathyways-repo
            cd pathyways-repo
            git clone https://${{secrets.ACCESS_TOKEN}}@github.com/JanMichaelSE/Pathways-Mentoring.git
            echo 'Deployment Successful from Actions'
