on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Node JS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          token: ${{secrets.ACCESS_TOKEN}}

          script: |
            mkdir pathways-repo-1
            cd pathways-repo-1
            git clone git@github.com:JanMichaelSE/Pathways-Mentoring.git
            echo 'Deployment Successful from Actions'
