on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            mkdir pathyways-mentoring-repo-1
            cd pathyways-mentoring-repo-1
            git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
            git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
            git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
            git clone https://git:${{secrets.GITHUB_TOKEN}}@github.com:JanMichaelSE/Pathways-Mentoring.git
            echo 'Deployment Successful from Actions'
