on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Github
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          
      - name: Authenticate with Vm
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          
      - name: Deploy App
        run: |
            mkdir pathways-repo-4
            cd pathways-repo-4
            git clone git@github.com:JanMichaelSE/Pathways-Mentoring.git
            echo 'Deployment Successful from Actions'
